import type { Metadata } from 'next'
import { Alegreya } from 'next/font/google'
import './globals.scss'

const alegreya = Alegreya({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={alegreya.className} suppressHydrationWarning>
        {children}
      </body>
    </html>
  )
}
